# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calltime', models.DateTimeField(auto_now_add=True)),
                ('caller', models.CharField(max_length=33)),
            ],
        ),
    ]
